version: '3.8'

services:
    db:
        image: postgres:15
        restart: always
        container_name: postgres_container
        environment:
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data

    backend:
        build: .
        container_name: nestjs_app
        ports:
            - "3001:3001"
        depends_on:
            - db
        env_file:
            - .env
        command: sh -c "npm run typeorm:run && npm run start:prod"

volumes:
    pgdata:
